class_name HireCandidate
extends RefCounted

## One recruitable pawn on offer in the recruitment window (WI-22). Pure rolled
## data - identity, skills (mostly low with 1-2 standouts), 0-2 traits, and a
## computed price - generated by CrewManager and applied to the real pawn only
## once the hire's shuttle arrives. Round-trips through the save via to_dict /
## from_dict so a pending hire and the standing pool both persist.

var pawn_name: String = ""
var tint: Color = Color.WHITE
## skill id -> level (0..10). xp starts at 0 for a hire.
var skills: Dictionary[StringName, int] = {}
var trait_ids: Array[StringName] = []
var price: int = 0

## Stamps this candidate's rolled identity onto a freshly spawned pawn.
func apply_to(pawn: PawnBase) -> void:
	pawn.pawn_name = pawn_name
	pawn.tint = tint
	pawn.hire_price = price
	var skills_comp: PawnSkillsComponent = pawn.get_skills_component()
	if skills_comp != null:
		for id: StringName in skills:
			skills_comp.set_level(id, skills[id])
	var traits_comp: PawnTraitsComponent = pawn.get_traits_component()
	if traits_comp != null:
		var traits: Array[TraitData] = []
		for tid: StringName in trait_ids:
			var td: TraitData = TraitData.by_id(tid)
			if td != null:
				traits.append(td)
		traits_comp.set_traits(traits)

## Standout skills (level >= threshold), highest first - what the card shows.
func standout_skills(threshold: int = 3) -> Array[StringName]:
	var out: Array[StringName] = []
	for id: StringName in skills:
		if skills[id] >= threshold:
			out.append(id)
	out.sort_custom(func(a: StringName, b: StringName) -> bool: return skills[a] > skills[b])
	return out

func total_skill_levels() -> int:
	var total: int = 0
	for id: StringName in skills:
		total += skills[id]
	return total

# --- persistence --------------------------------------------------------------

func to_dict() -> Dictionary:
	var skills_out: Dictionary = {}
	for id: StringName in skills:
		skills_out[String(id)] = skills[id]
	var traits_out: Array = []
	for tid: StringName in trait_ids:
		traits_out.append(String(tid))
	return {
		"name": pawn_name,
		"tint": [tint.r, tint.g, tint.b, tint.a],
		"skills": skills_out,
		"traits": traits_out,
		"price": price,
	}

static func from_dict(data: Dictionary) -> HireCandidate:
	var candidate := HireCandidate.new()
	candidate.pawn_name = String(data.get("name", ""))
	var tint_arr: Array = data.get("tint", [])
	if tint_arr.size() >= 3:
		var alpha: float = float(tint_arr[3]) if tint_arr.size() >= 4 else 1.0
		candidate.tint = Color(float(tint_arr[0]), float(tint_arr[1]), float(tint_arr[2]), alpha)
	var skills_in: Dictionary = data.get("skills", {})
	for key: Variant in skills_in:
		candidate.skills[StringName(key)] = int(skills_in[key])
	for tid: Variant in data.get("traits", []):
		candidate.trait_ids.append(StringName(tid))
	candidate.price = int(data.get("price", 0))
	return candidate
