class_name HireCandidate
extends RefCounted

## One recruitable pawn on offer in the recruitment window (WI-22). Pure rolled
## data - identity, skills (mostly low with 1-2 standouts), 0-2 traits, and a
## computed price - generated by CrewManager and applied to the real pawn only
## once the hire's shuttle arrives. Round-trips through the save via to_dict /
## from_dict so a pending hire and the standing pool both persist.

var pawn_name: String = ""
var tint: Color = Color.WHITE
## skill id -> level (0..10). xp starts at 0 for a hire.
var skills: Dictionary[StringName, int] = {}
var trait_ids: Array[StringName] = []
var price: int = 0
## Which PawnData kind this candidate is (WI-47 M10). Rolled when the candidate
## is generated and saved with it, so a hire queued on a shuttle still arrives as
## the kind the player picked from the list. &"" = whatever CrewManager's fallback
## scene is, which is also every pre-M10 save.
var pawn_id: StringName = &""

## Stamps this candidate's rolled identity onto a freshly spawned pawn.
func apply_to(pawn: PawnBase) -> void:
	pawn.pawn_name = pawn_name
	pawn.tint = tint
	pawn.hire_price = price
	var skills_comp: PawnSkillsComponent = pawn.get_skills_component()
	if skills_comp != null:
		for id: StringName in skills:
			skills_comp.set_level(id, skills[id])
	var traits_comp: PawnTraitsComponent = pawn.get_traits_component()
	if traits_comp != null:
		var traits: Array[TraitData] = []
		for tid: StringName in trait_ids:
			var td: TraitData = TraitData.by_id(tid)
			if td != null:
				traits.append(td)
		traits_comp.set_traits(traits)

## A candidate's standout skills as one line - "Construction 7, Mining 5", or a
## plain note when everything rolled low. Lives here rather than on a panel
## because two surfaces render it (the recruitment window and WI-59's New Game
## setup screen), and one candidate should read as one sentence in both.
func skills_line() -> String:
	var parts: PackedStringArray = []
	for id: StringName in standout_skills():
		var def: SkillData = SkillData.by_id(id)
		var skill_name: String = def.display_name if def != null else String(id)
		parts.append("%s %d" % [skill_name, skills[id]])
	if parts.is_empty():
		return "No standout skills"
	return ", ".join(parts)

## The candidate's rolled traits, resolved. Unknown ids are dropped here and
## only here - a mod that declared a trait and was then uninstalled leaves one
## behind on a saved candidate, and every surface should skip it the same way.
func trait_data() -> Array[TraitData]:
	var out: Array[TraitData] = []
	for tid: StringName in trait_ids:
		var td: TraitData = TraitData.by_id(tid)
		if td != null:
			out.append(td)
	return out

## The candidate's traits as one line; "" when they rolled none, which callers
## use to skip the row entirely rather than print an empty label. A surface that
## wants each trait separately (to hang a tooltip off it, say) walks trait_data()
## instead - but both answers come from the same resolved list.
func traits_line() -> String:
	var parts: PackedStringArray = []
	for td: TraitData in trait_data():
		parts.append(td.display_name)
	return ", ".join(parts)

## Standout skills (level >= threshold), highest first - what the card shows.
func standout_skills(threshold: int = 3) -> Array[StringName]:
	var out: Array[StringName] = []
	for id: StringName in skills:
		if skills[id] >= threshold:
			out.append(id)
	out.sort_custom(func(a: StringName, b: StringName) -> bool: return skills[a] > skills[b])
	return out

func total_skill_levels() -> int:
	var total: int = 0
	for id: StringName in skills:
		total += skills[id]
	return total

# --- persistence --------------------------------------------------------------

func to_dict() -> Dictionary:
	var skills_out: Dictionary = {}
	for id: StringName in skills:
		skills_out[String(id)] = skills[id]
	var traits_out: Array = []
	for tid: StringName in trait_ids:
		traits_out.append(String(tid))
	var out: Dictionary = {
		"name": pawn_name,
		"tint": [tint.r, tint.g, tint.b, tint.a],
		"skills": skills_out,
		"traits": traits_out,
		"price": price,
	}
	# Omitted when unset so pre-M10 saves and post-M10 saves of a default-kind
	# candidate look identical.
	if pawn_id != &"":
		out["pawn"] = String(pawn_id)
	return out

static func from_dict(data: Dictionary) -> HireCandidate:
	var candidate := HireCandidate.new()
	candidate.pawn_name = String(data.get("name", ""))
	var tint_arr: Array = data.get("tint", [])
	if tint_arr.size() >= 3:
		var alpha: float = float(tint_arr[3]) if tint_arr.size() >= 4 else 1.0
		candidate.tint = Color(float(tint_arr[0]), float(tint_arr[1]), float(tint_arr[2]), alpha)
	var skills_in: Dictionary = data.get("skills", {})
	for key: Variant in skills_in:
		candidate.skills[StringName(key)] = int(skills_in[key])
	for tid: Variant in data.get("traits", []):
		candidate.trait_ids.append(StringName(tid))
	candidate.price = int(data.get("price", 0))
	candidate.pawn_id = StringName(String(data.get("pawn", "")))
	return candidate
